[package]
name = "XBurner"
version = "0.1.1"
edition = "2021"
description = "Advanced Keyboard Manager"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
env_logger = "0.11.6"
evdev = "0.12.2"
indexmap = { version = "2.7.0", features = ["serde"] }
lazy_static = "1.5.0"
libc = "0.2.169"
log = "0.4.22"
nix = { version = "0.29.0", features = ["feature", "process", "poll"] }
# nix = { version = "0.26.2" }
notify-rust = "4.11.3"
serde = {version = "1.0.217", features = ["derive"] }
serde_yaml = "0.9.34"
signal-hook = "0.3.17"
termcolor = "1.4.1"
x11rb = "0.13.1"
