[package]
name = "XBurner"
version = "0.1.0"
edition = "2021"
description = "Advanced Keyboard Manager"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.25", features = ["derive"] }
env_logger = "0.10.1"
evdev = "0.12.1"
indexmap = { version = "2.1.0", features = ["serde"] }
lazy_static = "1.4.0"
libc = "0.2.150"
log = "0.4.20"
nix = { version = "0.27.1", features = ["feature", "process", "poll"] }
# nix = { version = "0.26.2" }
notify-rust = "4.9.0"
serde = {vesion = "1.0.136", features = ["derive"] }
serde_yaml = "0.9.27"
signal-hook = "0.3.17"
termcolor = "1.3.0"
x11rb = "0.12.0"
