[package]
name = "XBurner"
version = "0.1.0"
edition = "2021"
description = "Advanced Keyboard Manager"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-rc.9", features = ["derive"] }
env_logger = "0.9.0"
evdev = "0.11.3"
fork = "0.1.18"
indexmap = { version = "1.7.0", features = ["serde"] }
lazy_static = "1.4.0"
libc = "0.2.112"
log = "0.4.14"
nix = "0.23.1"
notify-rust = "4.5.5"
serde = {vesion = "1.0.132", features = ["derive"] }
serde_yaml = "0.8.23"
shlex = "1.1.0"
signal-hook = "0.3.13"
termcolor = "1.1.2"
x11rb = "0.9.0"

