[package]
name = "XBurner"
version = "0.1.0"
edition = "2021"
description = "Advanced Keyboard Manager"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.23", features = ["derive"] }
env_logger = "0.10.0"
evdev = "0.12.1"
indexmap = { version = "1.9.2", features = ["serde"] }
lazy_static = "1.4.0"
libc = "0.2.139"
log = "0.4.17"
nix = "0.26.2"
notify-rust = "4.8.0"
serde = {vesion = "1.0.136", features = ["derive"] }
serde_yaml = "0.9.17"
signal-hook = "0.3.15"
termcolor = "1.2.0"
x11rb = "0.11.1"

